parameters:
    app.security.admin_regex: "^/admin"
    app.security.api_regex: "^/api"

security:
    providers:
        app_admin_user_provider:
            id: sylius.admin_user_provider.email_or_name_based

    encoders:
        App\Entity\UserInterface: sha512

    firewalls:
        admin:
            switch_user: true
            context: admin
            pattern: "%app.security.admin_regex%"
            provider: app_admin_user_provider
            form_login:
                provider: app_admin_user_provider
                login_path: app_admin_login
                check_path: app_admin_login_check
                failure_path: app_admin_login
                default_target_path: app_admin_dashboard
                use_forward: false
                use_referer: true
                csrf_token_generator: security.csrf.token_manager
                csrf_parameter: _csrf_admin_security_token
                csrf_token_id: admin_authenticate
            remember_me:
                secret: "%kernel.secret%"
                path: /admin
                name: APP_ADMIN_REMEMBER_ME
                lifetime: 31536000
                remember_me_parameter: _remember_me
            logout:
                path: app_admin_logout
                target: app_admin_login
            anonymous: true

        oauth_token:
            pattern: "%app.security.api_regex%/oauth/v2/token"
            security: false

        api:
            pattern: "%app.security.api_regex%/.*"
            provider: app_admin_user_provider
#            fos_oauth: true
            stateless: true
            anonymous: true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: "%app.security.admin_regex%/_partial", role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: "%app.security.admin_regex%/_partial", role: ROLE_NO_ACCESS }

        - { path: "%app.security.admin_regex%/login", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "%app.security.api_regex%/login", role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: "%app.security.admin_regex%", role: ROLE_ADMIN }
        - { path: "%app.security.api_regex%/.*", role: ROLE_API_ACCESS }
